### ISSUE TITLE
feat: migrate to `Django` and `drf`

### ISSUE THREAD

**Issue by tokitouq** [tokitouq/MangaAPI#13]
Currently this project uses FastAPI, but now I'm thinking to rewrite this in django and django-rest-framework.
since I use this kinda scraping logics for mangacore ( a project for streaming mangas ), it would be better to try this in django and drf.

I'd like hear your opinions.

**Comment by baseplate-admin** [comment]
This is not necessary. Instead of writing this here, why not open an issue in [mainline coreproject](https://github.com/baseplate-admin/coreproject) ?

**Comment by tokitou-san** [comment]
> why not open an issue in [mainline coreproject](https://github.com/baseplate-admin/coreproject) ?

Yes, but mainline project is already using django x drf. Also I thought this would be a nice warmup for me :)

**Comment by baseplate-admin** [comment]
> Yes, but mainline project is already using django x drf. Also I thought this would be a nice warmup for me :)

Tattoo sucks

**Comment by tokitou-san** [comment]
> Tattoo sucks

Please dont use these words in the main repo. many ppl watch this project.
no repeat or you will be banned from coreproject.

**Comment by baseplate-admin** [comment]
>  no repeat or you will be banned from coreproject royaly

Tattoo is angry XD
